### PR TITLE
Implement custom theming to match Google's AOSP design

### PR DESCRIPTION
**Pull request by msfjarvis**
~Heavily WIP~ good to go!

Summary of changes:

- Upgrade to MDC 1.1.0
- Improve IDE rendering of views backed by dynamic data
- Expand app themes to include a proper palette of colours

### CODE REVIEW

**Comment by msfjarvis** [comment]
demo

**Comment by msfjarvis** [comment]
dark

**Comment by msfjarvis** [comment]
The dark theme seems to fail every single accessibility contrast parameter so I'll be revisiting the palette in the morning.

**Comment by zx2c4** [comment]
Dark mode looks a lot worse to me, especially the "generate" button. But I assume this is part of a larger plan, so feel free to squash this down to a single commit and merge.

**Comment by msfjarvis** [comment]
> Dark mode looks a lot worse to me, especially the "generate" button. But I assume this is part of a larger plan, so feel free to squash this down to a single commit and merge.

Generate will get redone into a text-only button in the next UI pass. What else feels worse? I'd like to address the problems

**Comment by zx2c4** [comment]
> What else feels worse?

Seems weird to have the top bar color be the same as the background, and the floating panels feel a bit prominent.

I'm not a designer though so my sense here is somewhat limited.

"What does PixelOS do?" should be the guiding design.

**Comment by zx2c4** [comment]
(When you merge, can you push to the git.zx2c4.com master repo, and that'll get pushed here? I'll work out syncing in the reverse direction later.)

**Comment by msfjarvis** [comment]
> > What else feels worse?
> 
> Seems weird to have the top bar color be the same as the background, and the floating panels feel a bit prominent.

With Android 10 Google's pushing app developers to adopt the practice of drawing apps from device edges and rendering behind system bars so matching color is actually a common and aesthetic practice in this space. Once this is merged I'll introduce a helper that will render the tunnel list under a semi-transparent navigation bar.

> I'm not a designer though so my sense here is somewhat limited.
> 
> "What does PixelOS do?" should be the guiding design.

Google's AOSP design guidelines are often slightly out of sync with what they recommend apps to do. The current difference seems to be rendering under system bars, which AOSP abandonware seems to not do but Google apps from the Play Store prefer to.

**Comment by zx2c4** [comment]
> With Android 10 Google's pushing app developers to adopt the practice of drawing apps from device edges and rendering behind system bars so matching color is actually a common and aesthetic practice in this space. Once this is merged I'll introduce a helper that will render the tunnel list under a semi-transparent navigation bar.

Okay.

> Google's AOSP design guidelines are often slightly out of sync with what they recommend apps to do. The current difference seems to be rendering under system bars, which AOSP abandonware seems to not do but Google apps from the Play Store prefer to.

I meant PixelOS because it seems like that's the OS that Google cares about, rather than AOSP. Goal is to look as close as possible to an OS component.

**Pull request closed without merging**
