### PR TITLE
libwg-go: use conn.Bind for socketfd peek

### PR DESCRIPTION
**Pull request by crawshaw**
This builds, but I'm still trying to get an android emulator setup. Will update this PR when I know the code actually runs.

If you're happy with this approach, I'll do the windows shims next.

### CODE REVIEW

**Comment by zx2c4** [comment]
LGTM. Thanks for doing this.

**Comment by crawshaw** [comment]
I haven't had any luck starting my apk yet, stuck on android signing:

`Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl945156778.tmp/base.apk has no certificates at entry AndroidManifest.xml]`

Also I ran into a build bug: editing `api-android.go` is not always enough for `./gradlew assembleRelease` to trigger a rebuild of the .so file.

**Comment by zx2c4** [comment]
Rather than dealing with certificate misery, try using `assembleDebug`.

**Comment by crawshaw** [comment]
Ah yes of course thanks. OK I added some logging on this end and confirmed that `wgGetSocketV4` is called and that PeekLookAtSocketFd4 returns a real fd when I enable a tunnel on the emulator.

**Comment by zx2c4** [comment]
Great. Once you apply the wireguard-go changes, just update the go.mod here and then I'll apply it.

**Comment by crawshaw** [comment]
Done. APK builds and loads.

**Comment by zx2c4** [comment]
Applied. Thanks.

wireguard-windows changes next, I guess?

**Comment by crawshaw** [comment]
Yes, I'll do windows tomorrow. More VMs to sort out...

**Pull request closed without merging**
