### PR TITLE
Add Hindi translation

### PR DESCRIPTION
**Pull request by theradcolor**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Applied, thanks!

**Comment by theradcolor** [comment]
> Applied, thanks!

Nice, thanks :)

**Comment by msfjarvis** [comment]
Would you mind providing your real name? We follow the kernel.org patch submission guidelines[1] which disallow anonymous or aliased contributions.


 1: https://www.kernel.org/doc/html/latest/process/submitting-patches.html#developer-s-certificate-of-origin-1-1

**Comment by theradcolor** [comment]
> Would you mind providing your real name? We follow the kernel.org [patch submission guidelines](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#developer-s-certificate-of-origin-1-1) which disallow anonymous or aliased contributions.
Sure, Shashank Baghel!

**Comment by zx2c4** [comment]
@theradcolor - would you consider updating your nice Hindi translation? We're now doing things over here, which should make it easier: https://crowdin.com/translate/WireGuard/all/en-hi

**Comment by theradcolor** [comment]
> @theradcolor - would you consider updating your nice Hindi translation? We're now doing things over here, which should make it easier: https://crowdin.com/translate/WireGuard/all/en-hi

Sure, I would like to contribute!

**Pull request merged**
